#!/bin/sh
# Regenerate the design-sync CSS entry. MUST run before package-build.mjs.
# The converter appends cssEntry RAW — it does not follow @import — so the
# entry has to be a real concatenation, not an import list.
set -e
cd "$(dirname "$0")/.."
{
  echo "/* GENERATED by .design-sync/build-css-entry.sh — do not edit. */"
  echo "/* tokens.css: the --token palette, type scale, spacing, radii */"
  cat src/styles/tokens.css
  echo "/* base.css: .t-* type utilities + .hit tap-target expander, applied by class name in src/ui */"
  cat src/styles/base.css
} > .design-sync/ds-entry.css
