"""Generate Vale's project vocabulary from readable word lists.

Vale reads `.vale/styles/config/vocabularies/Marinara/accept.txt`, where every
line is a regular expression. Writing those by hand means spelling out each
inflection and casing of every term, so instead keep plain word lists here and
expand them:

    python3 scripts/genvocab.py > .vale/styles/config/vocabularies/Marinara/accept.txt

Run that after editing a list, and commit both files.
"""

# Proper nouns: exact casing on purpose, so Vale.Terms flags "vite" -> "Vite".
proper = """
Archivo JSDoc Luma Mira Preact Radix Tabler Valibot Vite Vitest
"""

# Domain vocabulary: words Microsoft's word lists want swapped, which mean
# something specific here. Vale skips vocabulary terms in every check, so
# listing a word here exempts it without switching the whole rule off.
#   extract/extraction  claim extraction, not "remove"  (Microsoft.Wordiness)
#   glyph               an icon or type glyph, not "symbol"  (Microsoft.Jargon)
#   backend             the engine; the console really has one  (Microsoft.Avoid)
#   click               a precise input verb, not "select"  (Microsoft.UIVerbs)
#   accessible          as in accessible name  (Microsoft.Vocab)
#   disabled            a disabled control, not a person  (Microsoft.Accessibility)
domain = """
accessible backend click disabled extraction glyph
"""

# Jargon and common nouns: accept either casing and the usual inflections.
common = """
affordance agent attr autosave backlink boolean charset chiprail clearable compat
config copycheck debounce dedup dedupe deduplicate deps destructure
destructuring dev devtools discardable discoverability domsnap edu ellipsised
enum esc exceedance expander fullscreen greppable greyscale grouphead hardcode
hoc hotspot impactful implementer inline jsdom keydown keypress knip lgtm
loopback lorebook metaline misaligning mockup nullable numerics onboarding
oxlint padding param pressable proxied proxying refetch reflow reimplement repo
revisitable roleplay rollup scrollable scrollbar skimmable snake_case subline
substate tabbable tabindex teleport togglable tooltip tri triaged unauthored
unawaited unclipped undecide undeciding undrawn unenumerable unlayered unmocked
unmount unrendered unscoped unstyled untraced unwired upstream vendored
viewport virtualize wireframe
"""

# Tokens that also turn up fully capitalised in prose: DOM tags, file types,
# and UI button labels such as EXTRACT.
caps = """
css diff extract json textarea ui url
"""

# Identifiers and data keys that appear bare in prose. Keep this list minimal:
# an identifier inside a code span or fence is already skipped, so anything here
# is a word we chose to write as running text.
idents = """
add_link create_note node_modules npm savedAt sendBeacon sessionStorage
targetId timeline_event useState
"""

INFLECT = r"(s|es|d|ed|ing|'s)?"


def either_case(word):
    """`repo` -> `[Rr]epo`, so a sentence-initial capital still matches."""
    return f"[{word[0].upper()}{word[0]}]{word[1:]}"


def any_case(word):
    """`css` -> `[Cc][Ss][Ss]`, matching css, Css and CSS alike."""
    return "".join(f"[{c.upper()}{c}]" for c in word)


out = [
    "# Generated by scripts/genvocab.py -- edit the word lists there, not here.",
]
for heading, words, expand in (
    ("Proper nouns (exact casing enforced).", proper, lambda w: w),
    ("Domain vocabulary (see note above).", domain, either_case),
    ("Jargon and common nouns (either casing, usual inflections).", common, either_case),
    ("Tokens that also appear fully capitalised.", caps, any_case),
    ("Identifiers and data keys used bare in prose.", idents, either_case),
):
    out += ["", f"# {heading}"]
    suffix = "" if words is proper else INFLECT
    out += [expand(w) + suffix for w in sorted(set(words.split()))]

print("\n".join(out))
