"""Expand these word lists into the regexes Vale's accept.txt wants.

    python3 scripts/genvocab.py > .vale/styles/config/vocabularies/Luma/accept.txt
"""

# Exact casing on purpose, so Vale.Terms flags "vite" -> "Vite".
proper = """
Archivo JSDoc Luma Mira MiniSearch Playwright Preact Radix Rolldown Tabler
Valibot Vite Vitest
"""

# Words a Microsoft rule wants swapped, which mean something specific here.
domain = """
accessible backend click disabled extraction glyph
"""

# Jargon and common nouns: accept either casing and the usual inflections.
common = """
affordance agent attr autoadvance autoapplied autoapply autoinclude
brotli bundler
autosave backlink boolean charset chiprail clearable compat
config copycheck debounce dedup dedupe deduplicate deps destructure
deadexports destructuring dev devtools discardable discoverability domsnap
edu ellipsised eslint
enum esc exceedance expander fullscreen greppable greyscale grouphead hardcode
hoc hotspot impactful implementer inline jsdom keydown keypress knip lgtm
jscpd loopback lorebook metaline middleware misaligning mockup nullable
numerics onboarding
oxlint padding param pressable proxied proxying refetch reflow reimplement repo
revisitable roleplay rollup savebar scrollable scrollbar sirv skimmable
snake_case stylelint subline syncpack
substate tabbable tabindex teleport tokenizer togglable tooltip tri triaged
typescale uFuzzy unauthored
unawaited unclipped undecide undeciding undrawn unenumerable unlayered unmocked
unformatted unmount unrendered unscoped unstaged unstyled untraced unwired
upstream vendored viewport virtualize wireframe worktree
"""

# Tokens that also turn up fully capitalised in prose: DOM tags, file types,
# and UI button labels such as EXTRACT.
caps = """
css diff extract json textarea ui url
"""

# Identifiers written as running text. Keep minimal: code spans are skipped.
idents = """
add_link create_note node_modules npm savedAt sendBeacon sessionStorage
targetId timeline_event useState
"""

INFLECT = r"(s|es|d|ed|ing|'s)?"


def either_case(word):
    """`repo` -> `[Rr]epo`, so a sentence-initial capital still matches."""
    return f"[{word[0].upper()}{word[0]}]{word[1:]}"


def any_case(word):
    """`css` -> `[Cc][Ss][Ss]`, matching css, Css and CSS alike."""
    return "".join(f"[{c.upper()}{c}]" for c in word)


out = [
    "# Generated by scripts/genvocab.py -- edit the word lists there, not here.",
]
for heading, words, expand in (
    ("Proper nouns (exact casing enforced).", proper, lambda w: w),
    ("Domain vocabulary (see note above).", domain, either_case),
    ("Jargon and common nouns (either casing, usual inflections).", common, either_case),
    ("Tokens that also appear fully capitalised.", caps, any_case),
    ("Identifiers and data keys used bare in prose.", idents, either_case),
):
    out += ["", f"# {heading}"]
    suffix = "" if words is proper else INFLECT
    out += [expand(w) + suffix for w in sorted(set(words.split()))]

print("\n".join(out))
